# Generated by Django 2.1 on 2019-09-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='webiste',
            new_name='website',
        ),
    ]
