# Generated by Django 2.2.4 on 2019-09-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190908_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='webiste',
        ),
    ]
